[[plugins]]
repo = "Shougo/ddc.vim"
depends = [
    "denops.vim",
    "ddc-ui-native",
    "ddc-source-around",
    "ddc-source-lsp",
    "ddc-fuzzy",
]
on_event = "InsertEnter"
lua_post_source = '''
vim.fn["ddc#custom#patch_global"]({
    ui = "native",
    sources = { "around", "lsp" },
    sourceOptions = {
        _ = {
            matchers = { "matcher_fuzzy" },
            sorters = { "sorter_fuzzy" },
            ignoreCase = true,
            minAutoCompleteLength = 1,
        },
        around = { mark = "[arnd]" },
        lsp = { mark = "[lsp]" },
    },
})
vim.cmd([[call ddc#enable()]])
'''

# ui
[[plugins]]
repo = "Shougo/ddc-ui-native"

# source
## ddc-source-lsp config is in `no_lazy.toml`
[[plugins]]
repo = "Shougo/ddc-source-around"
[[plugins]]
repo = "matsui54/ddc-source-buffer"


# filter
[[plugins]]
repo = "tani/ddc-fuzzy"
