[[plugins]]
repo = "Shougo/ddc.vim"
depends = [
    "ddc-ui-native",
    "ddc-source-around",
    "ddc-fuzzy",
]
on_event = "InsertEnter"
lua_post_source = '''
vim.fn["ddc#custom#patch_global"]({
    ui = "native",
    sources = { "around" },
    sourceOptions = {
        _ = {
            matchers = { "matcher_fuzzy" },
            sorters = { "sorter_fuzzy" },
            ignoreCase = true,
            minAutoCompleteLength = 1,
        },
        around = {
            mark = "[arnd]",
        },
    },
})
vim.cmd([[call ddc#enable()]])
'''

# ui
[[plugins]]
repo = "Shougo/ddc-ui-native"

# source
[[plugins]]
repo = "Shougo/ddc-source-around"
[[plugins]]
repo = "matsui54/ddc-source-buffer"

# filter
[[plugins]]
repo = "tani/ddc-fuzzy"
