[[plugins]]
repo = "Shougo/ddu.vim"
on_func = "ddu#start"

# ui
[[plugins]]
repo = "Shougo/ddu-ui-ff"
on_func = "ddu#start"
depends = [
    "ddu.vim",
    "ddu-source-file_rec",
    "ddu-filter-fzf",
    "ddu-kind-file",
    "ddu-column-icon_filename"
]
lua_add = '''
    vim.api.nvim_create_autocmd("FileType", {
        pattern = "ddu-ff",
        group = vim.api.nvim_create_augroup("__ddu_ff", { clear = true }),
        callback = function()
            local opts = { noremap = true, silent = true, buffer = true }
            vim.keymap.set("n", "q", [[<cmd>call ddu#ui#async_action("quit")<cr>]], opts)
            vim.keymap.set("n", "<cr>", [[<cmd>call ddu#ui#async_action("itemAction")<cr>]], opts)
            vim.keymap.set("n", "i", [[<cmd>call ddu#ui#async_action("openFilterWindow")<cr>]], opts)
        end
    })
'''
lua_post_source = '''
    vim.fn["ddu#custom#patch_local"]("file_recursive", {
        ui = "ff",
        sources = {
            {
                name = { "file_rec" },
                options = {
                    matchers = {
                        "matcher_fzf",
                    },
                    sorters = {
                        "sorter_fzf",
                    },
                },
                params = {
                    ignoreDirectories = {
                        ".git",
                        ".venv",
                        ".vscode",
                        "__pycache__",
                        "node_modules",
                    },
                }
            },
        },
        kindOptions = {
            file = {
                defaultAction = "open",
            }
        },
    })
'''

# source
[[plugins]]
repo = "Shougo/ddu-source-file_rec"

# filter
[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"

# kind
[[plugins]]
repo = "Shougo/ddu-kind-file"

# column
[[plugins]]
repo = "Shougo/ddu-column-icon_filename"
