[[plugins]]
repo = "Shougo/ddu.vim"

# ui
[[plugins]]
repo = "Shougo/ddu-ui-filer"

# source
[[plugins]]
repo = "Shougo/ddu-source-file_rec"

# filter
[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"

# kind
[[plugins]]
repo = "Shougo/ddu-kind-file"

# column
[[plugins]]
repo = "Shougo/ddu-column-icon_filename"
