[[plugins]]
repo = "Shougo/ddu.vim"
on_func = "ddu#start"

# ui
[[plugins]]
repo = "Shougo/ddu-ui-ff"
depends = [
    "ddu.vim",
    "ddu-source-file_rec",
    "ddu-filter-fzf",
    "ddu-kind-file",
]
on_map = { n = "<leader>f" }
hooks_file = "~/.config/nvim/hooks/ddu-ui-ff.lua"

[[plugins]]
repo = "Shougo/ddu-ui-filer"
depends = [
    "ddu.vim",
    "ddu-source-file",
    "ddu-kind-file",
    "ddu-column-icon_filename",
]
on_map = { n = "<leader>e" }
hooks_file = "~/.config/nvim/hooks/ddu-ui-filer.lua"

# source
[[plugins]]
repo = "Shougo/ddu-source-file"
[[plugins]]
repo = "Shougo/ddu-source-file_rec"

# filter
[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"
[[plugins]]
repo = "yuki-yano/ddu-filter-fzf"

# kind
[[plugins]]
repo = "Shougo/ddu-kind-file"

# column
[[plugins]]
repo = "Shougo/ddu-column-icon_filename"
