[[plugins]]
repo = "windwp/nvim-autopairs"
on_event = "InsertEnter"
lua_source = '''
    require("nvim-autopairs").setup({
        check_ts = true,
    })
'''

[[plugins]]
repo = "hiphish/rainbow-delimiters.nvim"
on_event = ["BufNewFile", "BufReadPost"]
