[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

[[plugins]]
repo = "windwp/nvim-autopairs"
on_event = "InsertEnter"
lua_source = '''
    require("nvim-autopairs").setup({
        check_ts = true,
    })
'''

[[plugins]]
repo = "hiphish/rainbow-delimiters.nvim"
on_event = ["BufNewFile", "BufReadPost"]

[[plugins]]
repo = "nvimdev/indentmini.nvim"
on_event = ["BufNewFile", "BufReadPost"]
on_cmd = ["IndentToggle", "IndentEnable", "IndentDisable"]
lua_source = '''
    local indentmini_augroup = vim.api.nvim_create_augroup("__indentmini__", { clear = true })

    local function set_indentmini_highlights()
        local non_text = vim.api.nvim_get_hl(0, { name = "NonText" })
        local line_nr = vim.api.nvim_get_hl(0, { name = "LineNr" })
        vim.api.nvim_set_hl(0, "IndentLine", { fg = non_text.fg, nocombine = true })
        vim.api.nvim_set_hl(0, "IndentLineCurrent", { fg = line_nr.fg or non_text.fg, nocombine = true })
    end

    set_indentmini_highlights()
    vim.api.nvim_create_autocmd("ColorScheme", {
        group = indentmini_augroup,
        callback = set_indentmini_highlights,
    })

    require("indentmini").setup({
        char = "▏",
        minlevel = 1,
        only_current = false,
        exclude = { "help", "markdown", "text" },
    })
'''

[[plugins]]
repo = "folke/lazydev.nvim"
on_ft = "lua"
lua_source = '''
    require("lazydev").setup({})
'''

[[plugins]]
repo = "j-hui/fidget.nvim"
on_event = ["BufNewFile", "BufReadPost"]
lua_source = '''
    require("fidget").setup({})
'''

[[plugins]]
repo = "rebelot/heirline.nvim"
depends = [
    "nvim-web-devicons",
]
on_event = "UIEnter"
hooks_file = "$XDG_CONFIG_HOME/nvim/hooks/heirline.lua"

[[plugins]]
repo = "stevearc/conform.nvim"
hooks_file = "$XDG_CONFIG_HOME/nvim/hooks/conform.lua"
on_map = { n = "<leader>lf" }

[[plugins]]
repo = "kylechui/nvim-surround"
on_map = { n = ["ys", "cs", "ds"] }
lua_source = '''
    require("nvim-surround").setup({})
'''

[[plugins]]
repo = "norcalli/nvim-colorizer.lua"
on_event = ["BufNewFile", "BufReadPost"]
lua_source = '''
    require("colorizer").setup()
'''
